import { Ionicons } from '@expo/vector-icons';
import { LinearGradient } from 'expo-linear-gradient';
import React, { useMemo, useState } from 'react';
import { Alert, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { AnimatedPressable, FadeInView } from '../components/Motion';
import { Panel } from '../components/UI';
import { useGate } from '../store/GateContext';
import { colors, gradients, spacing } from '../theme';
export function CreatePassScreen({ onBack, onCreated }: { onBack: () => void; onCreated: () => void }) {
 const { sites, createPass, loading } = useGate(); const [siteId,setSiteId]=useState(sites[0]?.id??''); const site=sites.find(x=>x.id===siteId); const [gate,setGate]=useState(site?.gateNames[0]??'A Kapısı'); const [block,setBlock]=useState('B Blok'); const [apartment,setApartment]=useState('18'); const [orderNumber,setOrderNumber]=useState(`DBG-${Math.floor(100000+Math.random()*899999)}`); const [note,setNote]=useState('Temassız teslimat'); const valid=useMemo(()=>Boolean(siteId&&gate.trim()&&block.trim()&&apartment.trim()&&orderNumber.trim()),[siteId,gate,block,apartment,orderNumber]);
 const submit=async()=>{ if(!valid)return; try{await createPass({siteId,gate,block,apartment,orderNumber,note,etaMinutes:6});onCreated();}catch(e){Alert.alert('Talep gönderilemedi',e instanceof Error?e.message:'Tekrar dene.');}};
 return <ScrollView keyboardShouldPersistTaps="handled" contentContainerStyle={s.content}><FadeInView style={s.header}><AnimatedPressable onPress={onBack}><View style={s.back}><Ionicons name="arrow-back" size={22} color={colors.text}/></View></AnimatedPressable><View><Text style={s.title}>Yeni CourierPass</Text><Text style={s.sub}>Gerçek talebi Supabase’e gönder</Text></View></FadeInView><Text style={s.label}>SİTE / REZİDANS</Text><ScrollView horizontal showsHorizontalScrollIndicator={false}>{sites.map(x=><AnimatedPressable key={x.id} onPress={()=>{setSiteId(x.id);setGate(x.gateNames[0]??'A Kapısı');}}><View style={[s.site,x.id===siteId&&s.active]}><Ionicons name={x.isDemo?'flask':'business'} size={18} color={x.id===siteId?colors.cyan:colors.textMuted}/><Text style={s.siteText}>{x.name}{x.isDemo?' • Demo':''}</Text></View></AnimatedPressable>)}</ScrollView>{!sites.length?<Panel><Text style={s.help}>Aktif site yok. Ayarlardan demo v0.0.2 yükleyebilirsin.</Text></Panel>:null}<Panel style={s.form} gradient><Field label="Kapı" value={gate} onChangeText={setGate}/><View style={s.row}><Field label="Blok" value={block} onChangeText={setBlock}/><Field label="Daire" value={apartment} onChangeText={setApartment}/></View><Field label="Sipariş numarası" value={orderNumber} onChangeText={setOrderNumber}/><Field label="Kurye notu" value={note} onChangeText={setNote}/></Panel><AnimatedPressable onPress={()=>void submit()} disabled={!valid||loading}><LinearGradient colors={valid?gradients.success:['#3A4C5D','#293B4C']} style={s.submit}><Ionicons name="paper-plane" size={21} color={colors.background}/><Text style={s.submitText}>{loading?'GÖNDERİLİYOR':'GÜVENLİĞE GÖNDER'}</Text></LinearGradient></AnimatedPressable></ScrollView>;
}
function Field({label,...props}:React.ComponentProps<typeof TextInput>&{label:string}){return <View style={s.field}><Text style={s.fieldLabel}>{label}</Text><TextInput {...props} style={s.input} placeholderTextColor={colors.textMuted}/></View>}
const s=StyleSheet.create({content:{padding:spacing.md,paddingBottom:45,gap:18},header:{flexDirection:'row',alignItems:'center',gap:11},back:{width:46,height:46,borderRadius:16,borderWidth:1,borderColor:colors.border,alignItems:'center',justifyContent:'center'},title:{color:colors.text,fontSize:23,fontWeight:'900'},sub:{color:colors.textSoft,fontSize:12,marginTop:3},label:{color:colors.textSoft,fontSize:11,fontWeight:'900'},site:{minHeight:48,paddingHorizontal:12,marginRight:8,borderRadius:15,borderWidth:1,borderColor:colors.border,flexDirection:'row',alignItems:'center',gap:8},active:{borderColor:colors.borderStrong,backgroundColor:'rgba(55,216,255,.1)'},siteText:{color:colors.text,fontSize:13,fontWeight:'800'},help:{color:colors.textSoft,fontSize:13},form:{gap:12},row:{flexDirection:'row',gap:10},field:{flex:1},fieldLabel:{color:colors.textSoft,fontSize:11,fontWeight:'800',marginBottom:6},input:{height:52,borderRadius:16,borderWidth:1,borderColor:colors.border,color:colors.text,paddingHorizontal:12,fontSize:14,fontWeight:'700'},submit:{height:60,borderRadius:20,flexDirection:'row',alignItems:'center',justifyContent:'center',gap:9},submitText:{color:colors.background,fontSize:14,fontWeight:'900'}});
