import { Ionicons } from '@expo/vector-icons';
import React from 'react';
import { RefreshControl, ScrollView, StyleSheet, Text, View } from 'react-native';
import { AnimatedPressable, FadeInView, PulseDot } from '../components/Motion';
import { EmptyState, Panel } from '../components/UI';
import { useGate } from '../store/GateContext';
import { colors, spacing } from '../theme';
import { UserRole } from '../types';

const tones = { cyan: colors.cyan, purple: colors.purple, green: colors.green, orange: colors.orange, red: colors.red };

export function HistoryScreen({ role }: { role: UserRole }) {
  const gate = useGate();
  if (role === 'resident') return <ResidentNotifications />;
  return <ScrollView refreshControl={<RefreshControl refreshing={gate.refreshing} onRefresh={() => void gate.refresh()} tintColor={colors.cyan} />} contentContainerStyle={s.content}>
    <FadeInView style={s.header}><View><Text style={s.eyebrow}>DENETİM KAYITLARI</Text><Text style={s.title}>{role === 'courier' ? 'Hareketlerim' : role === 'security' ? 'Güvenlik işlemleri' : 'Site işlem geçmişi'}</Text><Text style={s.sub}>Supabase zaman çizelgesi • {gate.activities.length} hareket</Text></View><View style={s.headIcon}><Ionicons name="time" size={28} color={colors.cyan} /></View></FadeInView>
    {gate.activities.length ? <View>{gate.activities.map((item, index) => { const tone = tones[item.tone]; return <FadeInView key={item.id} delay={50 + index * 25} style={s.item}><View style={s.rail}>{index < gate.activities.length - 1 ? <View style={s.line} /> : null}<View style={[s.dot, { borderColor: tone }]}><PulseDot color={tone} size={7} /></View></View><Panel style={[s.card, { borderColor: `${tone}45` }]} gradient><View style={[s.icon, { backgroundColor: `${tone}1C` }]}><Ionicons name={item.icon as keyof typeof Ionicons.glyphMap} size={21} color={tone} /></View><View style={s.copy}><Text style={s.itemTitle}>{item.title}</Text><Text style={s.itemText}>{item.detail}</Text>{item.isDemo ? <Text style={s.demo}>DEMO</Text> : null}</View><Text style={s.time}>{item.time}</Text></Panel></FadeInView>; })}</View> : <EmptyState icon="time-outline" title="Henüz hareket yok" description="CourierPass, AirPass ve güvenlik işlemleri burada görünecek." />}
  </ScrollView>;
}

function ResidentNotifications() {
  const gate = useGate();
  return <ScrollView refreshControl={<RefreshControl refreshing={gate.refreshing} onRefresh={() => void gate.refresh()} tintColor={colors.orange} />} contentContainerStyle={s.content}><FadeInView style={s.header}><View><Text style={[s.eyebrow, { color: colors.orange }]}>SAKİN BİLDİRİMLERİ</Text><Text style={s.title}>Bildirim geçmişi</Text><Text style={s.sub}>Olumlu kurye eşleşmeleri, misafir ve aidat hareketleri</Text></View><View style={[s.headIcon, { borderColor: 'rgba(255,179,92,.4)' }]}><Ionicons name="notifications" size={28} color={colors.orange} /></View></FadeInView>{gate.notifications.length ? <View style={s.notificationList}>{gate.notifications.map((item, index) => <FadeInView key={item.id} delay={50 + index * 20}><AnimatedPressable onPress={() => !item.readAt && void gate.markNotificationRead(item.id)}><Panel style={[s.notification, !item.readAt && s.unread]} gradient><View style={[s.icon, { backgroundColor: item.kind.includes('dues') ? 'rgba(255,179,92,.14)' : item.kind.includes('visitor') ? 'rgba(67,231,162,.14)' : 'rgba(55,216,255,.14)' }]}><Ionicons name={item.kind.includes('dues') ? 'wallet' : item.kind.includes('visitor') ? 'people' : 'navigate'} size={22} color={item.kind.includes('dues') ? colors.orange : item.kind.includes('visitor') ? colors.green : colors.cyan} /></View><View style={s.copy}><Text style={s.itemTitle}>{item.title}</Text><Text style={s.itemText}>{item.body}</Text><Text style={s.notificationTime}>{new Date(item.createdAt).toLocaleString('tr-TR')}</Text></View>{!item.readAt ? <View style={s.unreadDot} /> : null}</Panel></AnimatedPressable></FadeInView>)}</View> : <EmptyState icon="notifications-outline" title="Bildirim yok" description="Adresinle olumlu eşleşen kurye, VisitorPass ve aidat bildirimleri burada görünür." />}</ScrollView>;
}

const s = StyleSheet.create({
  content: { padding: spacing.md, paddingTop: 12, paddingBottom: 114, gap: 20 }, header: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }, eyebrow: { color: colors.cyan, fontSize: 12, fontWeight: '900', letterSpacing: 1 }, title: { color: colors.text, fontSize: 28, fontWeight: '900', marginTop: 4 }, sub: { color: colors.textSoft, fontSize: 12, lineHeight: 17, marginTop: 4, maxWidth: 280 }, headIcon: { width: 55, height: 55, borderRadius: 19, borderWidth: 1, borderColor: colors.borderStrong, alignItems: 'center', justifyContent: 'center' }, item: { flexDirection: 'row', minHeight: 98 }, rail: { width: 28, alignItems: 'center' }, line: { position: 'absolute', top: 23, bottom: -23, width: 2, backgroundColor: colors.borderStrong }, dot: { width: 21, height: 21, borderRadius: 11, borderWidth: 2, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.background }, card: { flex: 1, marginBottom: 10, flexDirection: 'row', alignItems: 'center', gap: 10 }, icon: { width: 45, height: 45, borderRadius: 15, alignItems: 'center', justifyContent: 'center' }, copy: { flex: 1 }, itemTitle: { color: colors.text, fontSize: 14, fontWeight: '900' }, itemText: { color: colors.textSoft, fontSize: 12, lineHeight: 17, marginTop: 3 }, time: { color: colors.textMuted, fontSize: 10, fontWeight: '800' }, demo: { color: colors.orange, fontSize: 8, fontWeight: '900', marginTop: 4 }, notificationList: { gap: 9 }, notification: { flexDirection: 'row', alignItems: 'center', gap: 10 }, unread: { borderColor: 'rgba(255,179,92,.45)' }, unreadDot: { width: 8, height: 8, borderRadius: 8, backgroundColor: colors.orange }, notificationTime: { color: colors.textMuted, fontSize: 9, marginTop: 5 },
});
