import { Ionicons } from '@expo/vector-icons';
import React from 'react';
import { RefreshControl, ScrollView, StyleSheet, Text, View } from 'react-native';
import { FadeInView, PulseDot } from '../components/Motion';
import { EmptyState, Panel } from '../components/UI';
import { useGate } from '../store/GateContext';
import { colors, spacing } from '../theme';
import { UserRole } from '../types';
const tones={cyan:colors.cyan,purple:colors.purple,green:colors.green,orange:colors.orange,red:colors.red};
export function HistoryScreen({role}:{role:UserRole}){const{activities,refreshing,refresh}=useGate();return <ScrollView refreshControl={<RefreshControl refreshing={refreshing} onRefresh={()=>void refresh()} tintColor={colors.cyan}/>} contentContainerStyle={s.content}><FadeInView style={s.header}><View><Text style={s.eyebrow}>DENETİM KAYITLARI</Text><Text style={s.title}>{role==='courier'?'Hareketlerim':'Geçiş geçmişi'}</Text><Text style={s.sub}>Supabase zaman çizelgesi • {activities.length} hareket</Text></View><View style={s.headIcon}><Ionicons name="time" size={28} color={colors.cyan}/></View></FadeInView>{activities.length?<View>{activities.map((x,i)=>{const tone=tones[x.tone];return <FadeInView key={x.id} delay={70+i*30} style={s.item}><View style={s.rail}>{i<activities.length-1?<View style={s.line}/>:null}<View style={[s.dot,{borderColor:tone}]}><PulseDot color={tone} size={7}/></View></View><Panel style={[s.card,{borderColor:`${tone}45`}]} gradient><View style={[s.icon,{backgroundColor:`${tone}1C`}]}><Ionicons name={x.icon as keyof typeof Ionicons.glyphMap} size={21} color={tone}/></View><View style={s.copy}><Text style={s.itemTitle}>{x.title}</Text><Text style={s.itemText}>{x.detail}</Text>{x.isDemo?<Text style={s.demo}>DEMO</Text>:null}</View><Text style={s.time}>{x.time}</Text></Panel></FadeInView>})}</View>:<EmptyState icon="time-outline" title="Henüz hareket yok" description="Gerçek veya isteğe bağlı demo geçişleri burada görünecek."/>}</ScrollView>}
const s=StyleSheet.create({content:{padding:spacing.md,paddingTop:12,paddingBottom:114,gap:22},header:{flexDirection:'row',alignItems:'center',justifyContent:'space-between'},eyebrow:{color:colors.cyan,fontSize:12,fontWeight:'900',letterSpacing:1},title:{color:colors.text,fontSize:29,fontWeight:'900',marginTop:4},sub:{color:colors.textSoft,fontSize:13,marginTop:4},headIcon:{width:55,height:55,borderRadius:19,borderWidth:1,borderColor:colors.borderStrong,alignItems:'center',justifyContent:'center'},item:{flexDirection:'row',minHeight:99},rail:{width:28,alignItems:'center'},line:{position:'absolute',top:23,bottom:-23,width:2,backgroundColor:colors.borderStrong},dot:{width:21,height:21,borderRadius:11,borderWidth:2,alignItems:'center',justifyContent:'center',backgroundColor:colors.background},card:{flex:1,marginBottom:11,flexDirection:'row',alignItems:'center',gap:11},icon:{width:45,height:45,borderRadius:15,alignItems:'center',justifyContent:'center'},copy:{flex:1},itemTitle:{color:colors.text,fontSize:15,fontWeight:'900'},itemText:{color:colors.textSoft,fontSize:13,marginTop:4},time:{color:colors.textMuted,fontSize:11,fontWeight:'800'},demo:{color:colors.orange,fontSize:9,fontWeight:'900',marginTop:5}});
