import { Ionicons } from '@expo/vector-icons';
import React from 'react';
import { ScrollView, StyleSheet, Text, View } from 'react-native';
import { FadeInView } from '../components/Motion';
import { Panel } from '../components/UI';
import { useDemo } from '../store/DemoContext';
import { colors, spacing } from '../theme';
import { UserRole } from '../types';

const toneMap = { cyan: colors.cyan, purple: colors.purple, green: colors.green, orange: colors.orange, red: colors.red };
export function HistoryScreen({ role }: { role: UserRole }) {
  const { activities } = useDemo();
  return <ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={styles.content}>
    <FadeInView style={styles.header}><View><Text style={styles.eyebrow}>DENETİM KAYITLARI</Text><Text style={styles.title}>{role === 'courier' ? 'Hareketlerim' : 'Geçiş geçmişi'}</Text><Text style={styles.subtitle}>Yerel demo zaman çizelgesi • {activities.length} hareket</Text></View><View style={styles.icon}><Ionicons name="time" size={25} color={colors.cyan} /></View></FadeInView>
    <FadeInView delay={80}><Panel style={styles.summary}><View><Text style={styles.summaryValue}>{activities.length}</Text><Text style={styles.summaryLabel}>Toplam hareket</Text></View><View style={styles.summaryDivider} /><View><Text style={[styles.summaryValue, { color: colors.green }]}>%98</Text><Text style={styles.summaryLabel}>Başarılı geçiş</Text></View><View style={styles.summaryDivider} /><View><Text style={[styles.summaryValue, { color: colors.orange }]}>18 sn</Text><Text style={styles.summaryLabel}>Ort. onay</Text></View></Panel></FadeInView>
    <View style={styles.timeline}>{activities.map((activity, index) => { const tone = toneMap[activity.tone]; return <FadeInView key={activity.id} delay={120 + index * 35} style={styles.item}><View style={styles.rail}>{index < activities.length - 1 ? <View style={styles.line} /> : null}<View style={[styles.dot, { borderColor: tone }]}><View style={[styles.dotInner, { backgroundColor: tone }]} /></View></View><Panel style={styles.card}><View style={[styles.activityIcon, { backgroundColor: `${tone}18` }]}><Ionicons name={activity.icon as keyof typeof Ionicons.glyphMap} size={19} color={tone} /></View><View style={styles.copy}><Text style={styles.activityTitle}>{activity.title}</Text><Text style={styles.activityDetail}>{activity.detail}</Text></View><Text style={styles.time}>{activity.time}</Text></Panel></FadeInView>; })}</View>
  </ScrollView>;
}
const styles = StyleSheet.create({ content: { padding: spacing.md, paddingTop: 12, paddingBottom: 112, gap: 20 }, header: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }, eyebrow: { color: colors.cyan, fontSize: 9, fontWeight: '900', letterSpacing: 1 }, title: { color: colors.text, fontSize: 25, fontWeight: '900', marginTop: 3 }, subtitle: { color: colors.textSoft, fontSize: 10, marginTop: 3 }, icon: { width: 48, height: 48, borderRadius: 17, backgroundColor: 'rgba(55,216,255,.09)', alignItems: 'center', justifyContent: 'center' }, summary: { flexDirection: 'row', justifyContent: 'space-around', alignItems: 'center' }, summaryValue: { color: colors.cyan, fontSize: 18, fontWeight: '900', textAlign: 'center' }, summaryLabel: { color: colors.textMuted, fontSize: 8, marginTop: 3 }, summaryDivider: { width: 1, height: 34, backgroundColor: colors.border }, timeline: { gap: 0 }, item: { flexDirection: 'row', minHeight: 84 }, rail: { width: 25, alignItems: 'center' }, line: { position: 'absolute', top: 20, bottom: -20, width: 1, backgroundColor: colors.borderStrong }, dot: { width: 17, height: 17, borderRadius: 10, borderWidth: 2, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.background }, dotInner: { width: 5, height: 5, borderRadius: 5 }, card: { flex: 1, marginBottom: 10, flexDirection: 'row', alignItems: 'center', gap: 10 }, activityIcon: { width: 39, height: 39, borderRadius: 14, alignItems: 'center', justifyContent: 'center' }, copy: { flex: 1 }, activityTitle: { color: colors.text, fontSize: 12, fontWeight: '800' }, activityDetail: { color: colors.textSoft, fontSize: 9, marginTop: 3 }, time: { color: colors.textMuted, fontSize: 9, fontWeight: '700' } });
