import { Ionicons } from '@expo/vector-icons';
import { LinearGradient } from 'expo-linear-gradient';
import React from 'react';
import { RefreshControl, ScrollView, StyleSheet, Text, View } from 'react-native';
import { FadeInView, FloatingView } from '../components/Motion';
import { EmptyState, LiveBadge, MetricCard, Panel, SectionTitle } from '../components/UI';
import { useGate } from '../store/GateContext';
import { colors, gradients, radius, spacing } from '../theme';
export function ManagementHome(){const{sites,passes,refreshing,refresh,release}=useGate();const waiting=passes.filter(x=>x.status==='waiting').length;const completed=passes.filter(x=>x.status==='completed').length;const real=passes.filter(x=>!x.isDemo).length;return <ScrollView refreshControl={<RefreshControl refreshing={refreshing} onRefresh={()=>void refresh()} tintColor={colors.cyan}/>} contentContainerStyle={s.content}><FadeInView style={s.header}><View><Text style={s.eyebrow}>SİTE YÖNETİM MERKEZİ</Text><Text style={s.title}>DraBornGate</Text><Text style={s.sub}>İzole Supabase operasyonu • v{release?.version??'0.0.2'}</Text></View><LiveBadge label="CANLI"/></FadeInView><FadeInView delay={70}><LinearGradient colors={gradients.management} style={s.hero}><View><Text style={s.heroLabel}>GERÇEK KAYIT SAYISI</Text><Text style={s.heroValue}>{real}</Text><Text style={s.heroText}>Demo kayıtları ayrı işaretlenir.</Text></View><FloatingView style={s.heroIcon}><Ionicons name="analytics" size={40} color={colors.white}/></FloatingView></LinearGradient></FadeInView><FadeInView delay={130} style={s.metrics}><MetricCard label="Aktif site" value={String(sites.length)} icon="business" tone={colors.cyan}/><MetricCard label="Bekleyen" value={String(waiting)} icon="time" tone={colors.orange}/><MetricCard label="Tamamlanan" value={String(completed)} icon="checkmark-done" tone={colors.green}/></FadeInView><FadeInView delay={190}><SectionTitle title="Site görünümü"/>{sites.length?<View style={s.list}>{sites.map(site=><Panel key={site.id} style={s.site} gradient><View style={[s.siteIcon,{backgroundColor:site.isDemo?'rgba(255,179,92,.15)':'rgba(55,216,255,.13)'}]}><Ionicons name={site.isDemo?'flask':'business'} size={24} color={site.isDemo?colors.orange:colors.cyan}/></View><View style={s.copy}><Text style={s.siteName}>{site.name}</Text><Text style={s.siteText}>{site.address??'Adres belirtilmedi'} • {site.gateNames.length} kapı</Text></View><Text style={{color:site.isDemo?colors.orange:colors.green,fontSize:9,fontWeight:'900'}}>{site.isDemo?'DEMO':'GERÇEK'}</Text></Panel>)}</View>:<EmptyState icon="business-outline" title="Site kaydı yok" description="Gerçek site veya ayarlardan isteğe bağlı demo bekleniyor."/>}</FadeInView><FadeInView delay={240}><SectionTitle title="Veritabanı ayrımı"/><Panel gradient><Row icon="server" title="Şema" value="draborngate" tone={colors.purple}/><Row icon="albums" title="Tablo öneki" value="dkd_gate_*" tone={colors.cyan}/><Row icon="people" title="Ortak kimlik" value="auth.users" tone={colors.green}/><Row icon="key" title="Android versionCode" value="1" tone={colors.orange}/></Panel></FadeInView></ScrollView>}
function Row({icon,title,value,tone}:{icon:keyof typeof Ionicons.glyphMap;title:string;value:string;tone:string}){return <View style={s.row}><View style={[s.rowIcon,{backgroundColor:`${tone}1A`}]}><Ionicons name={icon} size={20} color={tone}/></View><Text style={s.rowTitle}>{title}</Text><Text style={[s.rowValue,{color:tone}]}>{value}</Text></View>}
const s=StyleSheet.create({content:{padding:spacing.md,paddingTop:12,paddingBottom:114,gap:22},header:{flexDirection:'row',justifyContent:'space-between',alignItems:'center'},eyebrow:{color:colors.magenta,fontSize:12,fontWeight:'900',letterSpacing:1},title:{color:colors.text,fontSize:29,fontWeight:'900',marginTop:4},sub:{color:colors.textSoft,fontSize:13,marginTop:4},hero:{borderRadius:radius.xl,padding:21,flexDirection:'row',justifyContent:'space-between',alignItems:'center',borderWidth:1,borderColor:'rgba(255,255,255,.2)'},heroLabel:{color:'rgba(255,255,255,.78)',fontSize:11,fontWeight:'900'},heroValue:{color:colors.white,fontSize:40,fontWeight:'900'},heroText:{color:'rgba(255,255,255,.84)',fontSize:12},heroIcon:{width:75,height:75,borderRadius:25,backgroundColor:'rgba(255,255,255,.14)',alignItems:'center',justifyContent:'center'},metrics:{flexDirection:'row',gap:9},list:{gap:10},site:{flexDirection:'row',alignItems:'center',gap:11},siteIcon:{width:48,height:48,borderRadius:16,alignItems:'center',justifyContent:'center'},copy:{flex:1},siteName:{color:colors.text,fontSize:15,fontWeight:'900'},siteText:{color:colors.textSoft,fontSize:12,marginTop:4},row:{minHeight:62,flexDirection:'row',alignItems:'center',gap:10,borderBottomWidth:1,borderBottomColor:colors.border},rowIcon:{width:40,height:40,borderRadius:14,alignItems:'center',justifyContent:'center'},rowTitle:{flex:1,color:colors.text,fontSize:14,fontWeight:'800'},rowValue:{fontSize:13,fontWeight:'900'}});
