import { Ionicons } from '@expo/vector-icons';
import React, { useState } from 'react';
import { RefreshControl, ScrollView, StyleSheet, Text, View } from 'react-native';
import { AnimatedPressable, FadeInView } from '../components/Motion';
import { PassCard } from '../components/PassCard';
import { EmptyState, Panel } from '../components/UI';
import { useGate } from '../store/GateContext';
import { colors, spacing } from '../theme';
import { PassStatus, UserRole } from '../types';
type Filter='all'|PassStatus;const filters:Array<[Filter,string]>=[['all','Tümü'],['waiting','Bekleyen'],['approved','Onaylı'],['arrived','Kapıda'],['completed','Biten'],['rejected','Red']];
export function PassesScreen({role}:{role:UserRole}){const{passes,user,refreshing,refresh}=useGate();const[filter,setFilter]=useState<Filter>('all');if(role==='management')return <Rules/>;const scoped=role==='courier'?passes.filter(x=>x.courierUserId===user?.id):passes;const visible=scoped.filter(x=>filter==='all'||x.status===filter);return <ScrollView refreshControl={<RefreshControl refreshing={refreshing} onRefresh={()=>void refresh()} tintColor={colors.cyan}/>} contentContainerStyle={s.content}><FadeInView style={s.header}><View><Text style={s.eyebrow}>{role==='courier'?'COURIERPASS MERKEZİ':'GÜVENLİK KUYRUĞU'}</Text><Text style={s.title}>{role==='courier'?'Geçişlerim':'Tüm geçişler'}</Text><Text style={s.sub}>Supabase • {scoped.length} erişilebilir kayıt</Text></View><View style={s.headIcon}><Ionicons name="shield-checkmark" size={27} color={colors.cyan}/></View></FadeInView><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={s.filters}>{filters.map(([v,l])=><AnimatedPressable key={v} onPress={()=>setFilter(v)}><View style={[s.filter,filter===v&&s.active]}><Text style={[s.filterText,filter===v&&s.activeText]}>{l}</Text><Text style={s.count}>{v==='all'?scoped.length:scoped.filter(x=>x.status===v).length}</Text></View></AnimatedPressable>)}</ScrollView><View style={s.list}>{visible.length?visible.map((pass,i)=><FadeInView key={pass.id} delay={70+i*30}><PassCard pass={pass}/></FadeInView>):<EmptyState icon="file-tray-outline" title="Kayıt bulunamadı" description="Bu filtrede gerçek veya demo CourierPass yok."/>}</View></ScrollView>}
function Rules(){const rules=[['people','Ortak hesap','Kimlik DraBornGo ile aynı auth.users kaydını kullanır.'],['server','İzole veri','Ürün verileri yalnızca draborngate şemasındadır.'],['flask','Demo kontrolü','Demo ayarlardan sürüme bağlı yüklenir veya silinir.'],['key','Geçiş kodu','Kod yalnızca güvenlik yetkisiyle üretilir.']];return <ScrollView contentContainerStyle={s.content}><FadeInView style={s.header}><View><Text style={s.eyebrow}>YÖNETİM POLİTİKALARI</Text><Text style={s.title}>Geçiş kuralları</Text><Text style={s.sub}>v0.0.2 gerçek Supabase düzeni</Text></View></FadeInView><Panel gradient>{rules.map(([icon,title,text],i)=><View key={title} style={[s.rule,i<rules.length-1&&s.ruleBorder]}><View style={s.ruleIcon}><Ionicons name={icon as keyof typeof Ionicons.glyphMap} size={21} color={colors.purple}/></View><View style={{flex:1}}><Text style={s.ruleTitle}>{title}</Text><Text style={s.ruleText}>{text}</Text></View></View>)}</Panel></ScrollView>}
const s=StyleSheet.create({content:{padding:spacing.md,paddingTop:12,paddingBottom:114,gap:20},header:{flexDirection:'row',alignItems:'center',justifyContent:'space-between'},eyebrow:{color:colors.cyan,fontSize:12,fontWeight:'900',letterSpacing:1},title:{color:colors.text,fontSize:28,fontWeight:'900',marginTop:4},sub:{color:colors.textSoft,fontSize:13,marginTop:4},headIcon:{width:54,height:54,borderRadius:18,borderWidth:1,borderColor:colors.borderStrong,alignItems:'center',justifyContent:'center'},filters:{gap:8,paddingRight:15},filter:{height:42,paddingHorizontal:11,borderRadius:14,borderWidth:1,borderColor:colors.border,flexDirection:'row',alignItems:'center',gap:7},active:{borderColor:colors.borderStrong,backgroundColor:'rgba(55,216,255,.1)'},filterText:{color:colors.textSoft,fontSize:12,fontWeight:'800'},activeText:{color:colors.cyan},count:{color:colors.text,fontSize:10,fontWeight:'900'},list:{gap:12},rule:{minHeight:76,flexDirection:'row',alignItems:'center',gap:11},ruleBorder:{borderBottomWidth:1,borderBottomColor:colors.border},ruleIcon:{width:43,height:43,borderRadius:15,backgroundColor:'rgba(139,107,255,.12)',alignItems:'center',justifyContent:'center'},ruleTitle:{color:colors.text,fontSize:15,fontWeight:'900'},ruleText:{color:colors.textSoft,fontSize:12,marginTop:4}});
