import { Ionicons } from '@expo/vector-icons';
import React, { useState } from 'react';
import { Alert, RefreshControl, ScrollView, StyleSheet, Text, View } from 'react-native';
import { AnimatedPressable, FadeInView } from '../components/Motion';
import { PassCard } from '../components/PassCard';
import { EmptyState, Panel } from '../components/UI';
import { useGate } from '../store/GateContext';
import { colors, spacing } from '../theme';
import { PassStatus, UserRole } from '../types';

type Filter = 'all' | PassStatus;
const filters: Array<[Filter, string]> = [['all', 'Tümü'], ['waiting', 'Bekleyen'], ['approved', 'Onaylı'], ['arrived', 'Kapıda'], ['completed', 'Biten'], ['rejected', 'Red'], ['cancelled', 'İptal'], ['expired', 'Süresi dolan']];

export function PassesScreen({ role }: { role: UserRole }) {
  const gate = useGate();
  const [filter, setFilter] = useState<Filter>('all');
  if (role === 'resident') return <ResidentPasses />;
  if (role === 'management') return <ManagementRules />;
  const scoped = role === 'courier' ? gate.passes.filter((x) => x.courierUserId === gate.user?.id) : gate.passes;
  const visible = scoped.filter((x) => filter === 'all' || x.status === filter);
  const retry = async (id: string) => { try { await gate.retryPass(id); Alert.alert('Tekrar gönderildi', 'Önceki talep korunarak yeni kurye geçiş talebi oluşturuldu.'); } catch (e) { Alert.alert('Gönderilemedi', e instanceof Error ? e.message : 'Tekrar dene.'); } };
  const cancel = (id: string) => Alert.alert('Talebi iptal et', 'Bekleyen geçiş talebi iptal edilsin mi?', [{ text: 'Vazgeç', style: 'cancel' }, { text: 'İptal Et', style: 'destructive', onPress: async () => { try { await gate.updatePassStatus(id, 'cancelled'); } catch (e) { Alert.alert('İptal edilemedi', e instanceof Error ? e.message : 'Tekrar dene.'); } } }]);
  return <ScrollView refreshControl={<RefreshControl refreshing={gate.refreshing} onRefresh={() => void gate.refresh()} tintColor={colors.cyan} />} contentContainerStyle={s.content}>
    <FadeInView style={s.header}><View><Text style={s.eyebrow}>{role === 'courier' ? 'KURYE GEÇİŞ MERKEZİ' : 'GÜVENLİK KUYRUĞU'}</Text><Text style={s.title}>{role === 'courier' ? 'Geçişlerim' : 'Tüm geçişler'}</Text><Text style={s.sub}>Canlı sistem • {scoped.length} erişilebilir kayıt</Text></View><View style={s.headIcon}><Ionicons name="shield-checkmark" size={27} color={colors.cyan} /></View></FadeInView>
    <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={s.filters}>{filters.map(([value, label]) => <AnimatedPressable key={value} onPress={() => setFilter(value)}><View style={[s.filter, filter === value && s.active]}><Text style={[s.filterText, filter === value && s.activeText]}>{label}</Text><Text style={s.count}>{value === 'all' ? scoped.length : scoped.filter((x) => x.status === value).length}</Text></View></AnimatedPressable>)}</ScrollView>
    <View style={s.list}>{visible.length ? visible.map((pass, index) => <FadeInView key={pass.id} delay={50 + index * 25}><View style={s.passWrap}><PassCard pass={pass} showImage={role !== 'courier'} />{role === 'courier' && pass.status === 'waiting' ? <Action title="BEKLEYEN TALEBİ İPTAL ET" icon="trash" tone={colors.red} onPress={() => cancel(pass.id)} /> : null}{role === 'courier' && ['rejected', 'cancelled', 'expired'].includes(pass.status) ? <Action title="AYNI BİLGİLERLE TEKRAR TALEP GÖNDER" icon="refresh" tone={colors.cyan} onPress={() => void retry(pass.id)} /> : null}</View></FadeInView>) : <EmptyState icon="file-tray-outline" title="Kayıt bulunamadı" description="Bu filtrede gerçek veya örnek kurye geçiş kaydı yok." />}</View>
  </ScrollView>;
}
function ResidentPasses() {
  const gate = useGate();
  const visitors = gate.visitors.filter((x) => x.residentUserId === gate.user?.id);
  const charges = gate.duesCharges.filter((x) => x.residentUserId === gate.user?.id);
  return <ScrollView refreshControl={<RefreshControl refreshing={gate.refreshing} onRefresh={() => void gate.refresh()} tintColor={colors.orange} />} contentContainerStyle={s.content}><FadeInView style={s.header}><View><Text style={[s.eyebrow, { color: colors.orange }]}>SAKİN KAYITLARI</Text><Text style={s.title}>Misafir ve aidatlarım</Text><Text style={s.sub}>Ziyaretçi geçiş kodları ve ödeme geçmişi</Text></View><View style={s.headIcon}><Ionicons name="home" size={27} color={colors.orange} /></View></FadeInView><Text style={s.sectionTitle}>Ziyaretçi geçiş kayıtları</Text>{visitors.length ? <View style={s.list}>{visitors.map((x) => <Panel key={x.id} style={s.rowCard} gradient><View style={s.personIcon}><Ionicons name="person" size={22} color={colors.green} /></View><View style={s.copy}><Text style={s.itemTitle}>{x.guestName}</Text><Text style={s.itemText}>{x.plate || 'Plaka yok'} • {x.guestPhone || 'Telefon yok'} • {x.status.toUpperCase()}</Text>{x.rejectionReason ? <Text style={s.rejectText}>{x.rejectionReason}</Text> : null}</View><View><Text style={s.codeLabel}>KOD</Text><Text style={s.code}>{x.visitorCode}</Text></View></Panel>)}</View> : <EmptyState icon="people-outline" title="Misafir kaydı yok" description="Ana sayfadan yeni ziyaretçi geçişi oluşturabilirsin." />}<Text style={s.sectionTitle}>Aidat geçmişi</Text>{charges.length ? <View style={s.list}>{charges.map((x) => <Panel key={x.id} style={s.rowCard} gradient><Ionicons name={x.status === 'paid' ? 'checkmark-circle' : 'alert-circle'} size={25} color={x.status === 'paid' ? colors.green : colors.orange} /><View style={s.copy}><Text style={s.itemTitle}>{x.block} / Daire {x.apartment}</Text><Text style={s.itemText}>{x.status === 'paid' ? 'Ödendi' : 'Ödenmedi'}{x.paymentNote ? ` • ${x.paymentNote}` : ''}</Text></View><Text style={{ color: x.status === 'paid' ? colors.green : colors.orange, fontWeight: '900' }}>{x.amount.toLocaleString('tr-TR')} TL</Text></Panel>)}</View> : <EmptyState icon="wallet-outline" title="Aidat kaydı yok" description="Yönetim aidat dönemi oluşturduğunda burada görünür." />}</ScrollView>;
}
function ManagementRules() {
  const gate = useGate();
  return <ScrollView contentContainerStyle={s.content}><FadeInView style={s.header}><View><Text style={[s.eyebrow, { color: colors.purple }]}>YÖNETİM POLİTİKALARI</Text><Text style={s.title}>Kural sürümleri</Text><Text style={s.sub}>Aktif ve geçmiş site/kapı duyuruları</Text></View></FadeInView>{gate.rules.length ? <View style={s.list}>{gate.rules.map((x) => <Panel key={x.id} style={s.rowCard} gradient><Ionicons name={x.isCritical ? 'alert-circle' : 'document-text'} size={24} color={x.isCritical ? colors.red : colors.purple} /><View style={s.copy}><Text style={s.itemTitle}>{x.title} • v{x.version}</Text><Text style={s.itemText}>{x.body}</Text><Text style={s.ruleMeta}>{x.audience} • {x.scopeType} • {x.isActive ? 'AKTİF' : 'GEÇMİŞ SÜRÜM'}</Text></View></Panel>)}</View> : <EmptyState icon="document-outline" title="Kural yok" description="Ana yönetim ekranından site veya kapı kuralı ekleyebilirsin." />}</ScrollView>;
}
function Action({ title, icon, tone, onPress }: { title: string; icon: keyof typeof Ionicons.glyphMap; tone: string; onPress: () => void }) { return <AnimatedPressable onPress={onPress}><View style={[s.action, { borderColor: `${tone}60`, backgroundColor: `${tone}10` }]}><Ionicons name={icon} size={19} color={tone} /><Text style={[s.actionText, { color: tone }]}>{title}</Text></View></AnimatedPressable>; }
const s = StyleSheet.create({ content: { padding: spacing.md, paddingTop: 12, paddingBottom: 114, gap: 18 }, header: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }, eyebrow: { color: colors.cyan, fontSize: 12, fontWeight: '900', letterSpacing: 1 }, title: { color: colors.text, fontSize: 28, fontWeight: '900', marginTop: 4 }, sub: { color: colors.textSoft, fontSize: 12, marginTop: 4 }, headIcon: { width: 54, height: 54, borderRadius: 18, borderWidth: 1, borderColor: colors.borderStrong, alignItems: 'center', justifyContent: 'center' }, filters: { gap: 7, paddingRight: 14 }, filter: { height: 42, paddingHorizontal: 10, borderRadius: 14, borderWidth: 1, borderColor: colors.border, flexDirection: 'row', alignItems: 'center', gap: 6 }, active: { borderColor: colors.borderStrong, backgroundColor: 'rgba(55,216,255,.1)' }, filterText: { color: colors.textSoft, fontSize: 11, fontWeight: '900' }, activeText: { color: colors.cyan }, count: { color: colors.text, fontSize: 9, fontWeight: '900' }, list: { gap: 11 }, passWrap: { gap: 8 }, action: { minHeight: 48, borderRadius: 15, borderWidth: 1, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 7, paddingHorizontal: 8 }, actionText: { fontSize: 10, fontWeight: '900', textAlign: 'center' }, sectionTitle: { color: colors.text, fontSize: 19, fontWeight: '900', marginTop: 3 }, rowCard: { flexDirection: 'row', alignItems: 'center', gap: 9 }, personIcon: { width: 45, height: 45, borderRadius: 15, backgroundColor: 'rgba(67,231,162,.12)', alignItems: 'center', justifyContent: 'center' }, copy: { flex: 1 }, itemTitle: { color: colors.text, fontSize: 14, fontWeight: '900' }, itemText: { color: colors.textSoft, fontSize: 11, lineHeight: 16, marginTop: 3 }, rejectText: { color: colors.red, fontSize: 10, marginTop: 4 }, codeLabel: { color: colors.green, fontSize: 8, fontWeight: '900' }, code: { color: colors.text, fontSize: 19, fontWeight: '900', letterSpacing: 1.5 }, ruleMeta: { color: colors.purple, fontSize: 8, fontWeight: '900', marginTop: 5 } });
