import { Ionicons } from '@expo/vector-icons';
import React, { useState } from 'react';
import { ScrollView, StyleSheet, Text, View } from 'react-native';
import { AnimatedPressable, FadeInView } from '../components/Motion';
import { PassCard } from '../components/PassCard';
import { EmptyState, Panel } from '../components/UI';
import { useDemo } from '../store/DemoContext';
import { colors, radius, spacing } from '../theme';
import { PassStatus, UserRole } from '../types';

type Filter = 'all' | PassStatus;
const filterLabels: Array<[Filter, string]> = [['all', 'Tümü'], ['waiting', 'Bekleyen'], ['approved', 'Onaylı'], ['completed', 'Biten'], ['rejected', 'Red']];

export function PassesScreen({ role }: { role: UserRole }) {
  const { passes, courierProfile } = useDemo();
  const [filter, setFilter] = useState<Filter>('all');
  if (role === 'management') return <Rules />;
  const rolePasses = role === 'courier' ? passes.filter((pass) => pass.courierName === courierProfile.name) : passes;
  const visible = rolePasses.filter((pass) => filter === 'all' || pass.status === filter);
  return <ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={styles.content}>
    <FadeInView style={styles.header}><View><Text style={styles.eyebrow}>{role === 'courier' ? 'COURIERPASS MERKEZİ' : 'GÜVENLİK KUYRUĞU'}</Text><Text style={styles.title}>{role === 'courier' ? 'Geçişlerim' : 'Tüm geçişler'}</Text><Text style={styles.subtitle}>{rolePasses.length} demo kayıt • cihazda saklanıyor</Text></View><View style={styles.headerIcon}><Ionicons name="shield-checkmark" size={25} color={colors.cyan} /></View></FadeInView>
    <FadeInView delay={80}><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.filters}>{filterLabels.map(([value, label]) => <AnimatedPressable key={value} onPress={() => setFilter(value)}><View style={[styles.filter, filter === value && styles.filterActive]}><Text style={[styles.filterText, filter === value && styles.filterTextActive]}>{label}</Text><View style={[styles.count, filter === value && styles.countActive]}><Text style={styles.countText}>{value === 'all' ? rolePasses.length : rolePasses.filter((pass) => pass.status === value).length}</Text></View></View></AnimatedPressable>)}</ScrollView></FadeInView>
    <View style={styles.list}>{visible.length ? visible.map((pass, index) => <FadeInView key={pass.id} delay={120 + index * 45}><PassCard pass={pass} /></FadeInView>) : <EmptyState icon="file-tray-outline" title="Kayıt bulunamadı" description="Bu filtrede gösterilecek CourierPass bulunmuyor." />}</View>
  </ScrollView>;
}

function Rules() { const rules = [['bicycle', 'Kurye giriş saatleri', '07:00–23:30 arasında ana kapıdan giriş'], ['camera', 'Sipariş doğrulama', 'Sipariş numarası veya ekran görüntüsü zorunlu'], ['key', 'Geçiş kodu', 'Onay kodu tek teslimat için geçerlidir'], ['time', 'Maksimum içeride kalma', 'Teslimat için önerilen süre 15 dakika'], ['shield', 'Şüpheli durum', 'Güvenlik görevlisi talebi reddedebilir']]; return <ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={styles.content}><FadeInView style={styles.header}><View><Text style={styles.eyebrow}>YÖNETİM POLİTİKALARI</Text><Text style={styles.title}>Geçiş kuralları</Text><Text style={styles.subtitle}>DraBorn Marina Evleri • v0.1 demo</Text></View><View style={styles.headerIcon}><Ionicons name="document-lock" size={25} color={colors.purple} /></View></FadeInView><FadeInView delay={80}><Panel style={styles.rulePanel}>{rules.map(([icon, title, text], index) => <View key={title} style={[styles.rule, index < rules.length - 1 && styles.ruleBorder]}><View style={styles.ruleNumber}><Text style={styles.ruleNumberText}>{String(index + 1).padStart(2, '0')}</Text></View><View style={styles.ruleIcon}><Ionicons name={icon as keyof typeof Ionicons.glyphMap} size={19} color={colors.purple} /></View><View style={styles.ruleCopy}><Text style={styles.ruleTitle}>{title}</Text><Text style={styles.ruleText}>{text}</Text></View></View>)}</Panel></FadeInView><FadeInView delay={160}><Panel style={styles.notice}><Ionicons name="information-circle" size={22} color={colors.cyan} /><Text style={styles.noticeText}>Bu sürümde kurallar demo olarak sabittir. Supabase entegrasyonunda site yönetimi bunları düzenleyebilir.</Text></Panel></FadeInView></ScrollView>; }

const styles = StyleSheet.create({ content: { padding: spacing.md, paddingTop: 12, paddingBottom: 112, gap: 20 }, header: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, eyebrow: { color: colors.cyan, fontSize: 9, fontWeight: '900', letterSpacing: 1 }, title: { color: colors.text, fontSize: 25, fontWeight: '900', marginTop: 3 }, subtitle: { color: colors.textSoft, fontSize: 10, marginTop: 3 }, headerIcon: { width: 48, height: 48, borderRadius: 17, backgroundColor: 'rgba(55,216,255,.09)', alignItems: 'center', justifyContent: 'center' }, filters: { gap: 8, paddingRight: 15 }, filter: { height: 39, paddingHorizontal: 11, borderRadius: 14, borderWidth: 1, borderColor: colors.border, flexDirection: 'row', gap: 7, alignItems: 'center' }, filterActive: { borderColor: colors.borderStrong, backgroundColor: 'rgba(55,216,255,.09)' }, filterText: { color: colors.textSoft, fontSize: 10, fontWeight: '800' }, filterTextActive: { color: colors.cyan }, count: { minWidth: 20, height: 20, paddingHorizontal: 5, borderRadius: 8, backgroundColor: 'rgba(255,255,255,.05)', alignItems: 'center', justifyContent: 'center' }, countActive: { backgroundColor: 'rgba(55,216,255,.15)' }, countText: { color: colors.text, fontSize: 8, fontWeight: '900' }, list: { gap: 12 }, rulePanel: { paddingVertical: 3 }, rule: { minHeight: 76, flexDirection: 'row', alignItems: 'center', gap: 10 }, ruleBorder: { borderBottomWidth: 1, borderBottomColor: colors.border }, ruleNumber: { width: 28, height: 28, borderRadius: 10, backgroundColor: 'rgba(255,255,255,.04)', alignItems: 'center', justifyContent: 'center' }, ruleNumberText: { color: colors.textMuted, fontSize: 9, fontWeight: '900' }, ruleIcon: { width: 40, height: 40, borderRadius: 14, backgroundColor: 'rgba(139,107,255,.1)', alignItems: 'center', justifyContent: 'center' }, ruleCopy: { flex: 1 }, ruleTitle: { color: colors.text, fontSize: 12, fontWeight: '800' }, ruleText: { color: colors.textSoft, fontSize: 9, lineHeight: 14, marginTop: 4 }, notice: { flexDirection: 'row', alignItems: 'center', gap: 10, borderColor: 'rgba(55,216,255,.2)' }, noticeText: { flex: 1, color: colors.textSoft, fontSize: 9, lineHeight: 14 } });
