import { Ionicons } from '@expo/vector-icons';
import * as Haptics from 'expo-haptics';
import { LinearGradient } from 'expo-linear-gradient';
import React from 'react';
import { Alert, ScrollView, StyleSheet, Text, View } from 'react-native';
import { AnimatedPressable, FadeInView } from '../components/Motion';
import { Panel, SectionTitle } from '../components/UI';
import { useDemo } from '../store/DemoContext';
import { colors, gradients, radius, spacing } from '../theme';
import { UserRole } from '../types';

const labels: Record<UserRole, string> = { courier: 'Kurye Hesabı', security: 'Güvenlik Görevlisi', management: 'Site Yönetimi' };
export function ProfileScreen({ role, onSwitchRole }: { role: UserRole; onSwitchRole: () => void }) {
  const { courierProfile, resetDemo } = useDemo();
  const name = role === 'courier' ? courierProfile.name : role === 'security' ? 'Selim Kaya' : 'DraBorn Marina Yönetimi';
  const reset = () => Alert.alert('Demo verileri sıfırlansın mı?', 'Eklenen talepler silinir ve örnek veriler geri yüklenir.', [{ text: 'Vazgeç', style: 'cancel' }, { text: 'Sıfırla', style: 'destructive', onPress: async () => { await resetDemo(); void Haptics.notificationAsync(Haptics.NotificationFeedbackType.Success); } }]);
  return <ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={styles.content}>
    <FadeInView><LinearGradient colors={gradients.primary} style={styles.hero}><View style={styles.avatar}><Ionicons name={role === 'courier' ? 'bicycle' : role === 'security' ? 'shield' : 'business'} size={34} color={colors.white} /></View><Text style={styles.name}>{name}</Text><Text style={styles.role}>{labels[role]}</Text><View style={styles.verified}><Ionicons name="checkmark-circle" size={15} color={colors.green} /><Text style={styles.verifiedText}>Demo hesap doğrulandı</Text></View></LinearGradient></FadeInView>
    <FadeInView delay={90}><SectionTitle title="Hesap bilgileri" /><Panel style={styles.info}><Info icon="person" label="Ad Soyad" value={name} /><Info icon="call" label="Telefon" value={role === 'courier' ? courierProfile.phone : '0555 700 01 07'} /><Info icon="id-card" label="Yetki" value={labels[role]} />{role === 'courier' ? <Info icon="bicycle" label="Plaka" value={courierProfile.plate} /> : null}</Panel></FadeInView>
    <FadeInView delay={160}><SectionTitle title="Uygulama ve demo" /><View style={styles.menu}><Menu icon="swap-horizontal" title="Rol değiştir" detail="Kurye, güvenlik veya yönetim görünümüne geç" tone={colors.cyan} onPress={onSwitchRole} /><Menu icon="notifications" title="Bildirim tercihleri" detail="Geçiş ve onay uyarıları" tone={colors.orange} /><Menu icon="lock-closed" title="Gizlilik ve veri" detail="Tüm demo verileri yalnızca bu cihazda" tone={colors.green} /><Menu icon="refresh" title="Demo verilerini sıfırla" detail="Başlangıç örneklerini geri yükle" tone={colors.red} onPress={reset} /></View></FadeInView>
    <FadeInView delay={230} style={styles.version}><View style={styles.versionIcon}><Ionicons name="shield-half" size={21} color={colors.cyan} /></View><Text style={styles.versionName}>DraBornGate v0.1.0</Text><Text style={styles.versionText}>CourierPass Demo • Supabase kullanılmıyor</Text></FadeInView>
  </ScrollView>;
}
function Info({ icon, label, value }: { icon: keyof typeof Ionicons.glyphMap; label: string; value: string }) { return <View style={styles.infoRow}><View style={styles.infoIcon}><Ionicons name={icon} size={17} color={colors.cyan} /></View><View><Text style={styles.infoLabel}>{label}</Text><Text style={styles.infoValue}>{value}</Text></View></View>; }
function Menu({ icon, title, detail, tone, onPress }: { icon: keyof typeof Ionicons.glyphMap; title: string; detail: string; tone: string; onPress?: () => void }) { return <AnimatedPressable onPress={onPress} disabled={!onPress}><Panel style={styles.menuRow}><View style={[styles.menuIcon, { backgroundColor: `${tone}16` }]}><Ionicons name={icon} size={20} color={tone} /></View><View style={styles.menuCopy}><Text style={styles.menuTitle}>{title}</Text><Text style={styles.menuDetail}>{detail}</Text></View><Ionicons name="chevron-forward" size={18} color={colors.textMuted} /></Panel></AnimatedPressable>; }
const styles = StyleSheet.create({ content: { padding: spacing.md, paddingTop: 12, paddingBottom: 112, gap: 20 }, hero: { borderRadius: radius.xl, alignItems: 'center', padding: 24 }, avatar: { width: 76, height: 76, borderRadius: 27, backgroundColor: 'rgba(255,255,255,.15)', borderWidth: 1, borderColor: 'rgba(255,255,255,.22)', alignItems: 'center', justifyContent: 'center' }, name: { color: colors.white, fontSize: 22, fontWeight: '900', marginTop: 12 }, role: { color: 'rgba(255,255,255,.78)', fontSize: 10, fontWeight: '700', marginTop: 4 }, verified: { height: 30, borderRadius: radius.pill, paddingHorizontal: 10, marginTop: 11, backgroundColor: 'rgba(6,16,29,.25)', flexDirection: 'row', gap: 6, alignItems: 'center' }, verifiedText: { color: colors.white, fontSize: 9, fontWeight: '800' }, info: { paddingVertical: 3 }, infoRow: { minHeight: 62, flexDirection: 'row', alignItems: 'center', gap: 10, borderBottomWidth: 1, borderBottomColor: colors.border }, infoIcon: { width: 37, height: 37, borderRadius: 13, backgroundColor: 'rgba(55,216,255,.08)', alignItems: 'center', justifyContent: 'center' }, infoLabel: { color: colors.textMuted, fontSize: 8, fontWeight: '700' }, infoValue: { color: colors.text, fontSize: 11, fontWeight: '800', marginTop: 3 }, menu: { gap: 9 }, menuRow: { flexDirection: 'row', alignItems: 'center', gap: 10 }, menuIcon: { width: 43, height: 43, borderRadius: 15, alignItems: 'center', justifyContent: 'center' }, menuCopy: { flex: 1 }, menuTitle: { color: colors.text, fontSize: 12, fontWeight: '800' }, menuDetail: { color: colors.textSoft, fontSize: 9, marginTop: 4 }, version: { alignItems: 'center', paddingVertical: 10 }, versionIcon: { width: 42, height: 42, borderRadius: 16, backgroundColor: 'rgba(55,216,255,.08)', alignItems: 'center', justifyContent: 'center' }, versionName: { color: colors.text, fontSize: 12, fontWeight: '800', marginTop: 8 }, versionText: { color: colors.textMuted, fontSize: 9, marginTop: 3 } });
