import { Ionicons } from '@expo/vector-icons';
import * as Haptics from 'expo-haptics';
import { LinearGradient } from 'expo-linear-gradient';
import React, { useState } from 'react';
import { Alert, ScrollView, StyleSheet, Text, View } from 'react-native';
import { AnimatedPressable, FadeInView } from '../components/Motion';
import { PassCard } from '../components/PassCard';
import { LiveBadge, MetricCard, Panel, SectionTitle } from '../components/UI';
import { useDemo } from '../store/DemoContext';
import { colors, gradients, radius, spacing } from '../theme';
import { CourierPass } from '../types';

type Filter = 'waiting' | 'approved' | 'all';

export function SecurityHome() {
  const { passes, updatePassStatus } = useDemo();
  const [filter, setFilter] = useState<Filter>('waiting');
  const visible = passes.filter((pass) => filter === 'all' ? !['completed', 'rejected'].includes(pass.status) : pass.status === filter);
  const waiting = passes.filter((pass) => pass.status === 'waiting').length;
  const approved = passes.filter((pass) => pass.status === 'approved').length;

  const approve = (pass: CourierPass) => { updatePassStatus(pass.id, 'approved'); void Haptics.notificationAsync(Haptics.NotificationFeedbackType.Success); };
  const reject = (pass: CourierPass) => Alert.alert('Talebi reddet', `${pass.courierName} için geçiş reddedilsin mi?`, [{ text: 'Vazgeç', style: 'cancel' }, { text: 'Reddet', style: 'destructive', onPress: () => updatePassStatus(pass.id, 'rejected', 'Güvenlik doğrulaması başarısız') }]);

  return <ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={styles.content}>
    <FadeInView style={styles.header}><View><Text style={styles.eyebrow}>GÜVENLİK OPERASYONU</Text><Text style={styles.title}>DraBorn Marina</Text><Text style={styles.subtitle}>A Kapısı • Selim Kaya vardiyada</Text></View><LiveBadge /></FadeInView>
    <FadeInView delay={70}><LinearGradient colors={gradients.primary} style={styles.hero}><View style={styles.heroIcon}><Ionicons name="shield-checkmark" size={32} color={colors.white} /></View><View style={styles.heroCopy}><Text style={styles.heroLabel}>KAPI GÜVENLİK SKORU</Text><Text style={styles.heroValue}>%98.4</Text><Text style={styles.heroText}>Tüm sistemler aktif • Ortalama onay 18 sn</Text></View><Ionicons name="radio" size={24} color={colors.white} /></LinearGradient></FadeInView>
    <FadeInView delay={130} style={styles.metrics}><MetricCard label="Bekleyen" value={String(waiting)} icon="time" tone={colors.orange} /><MetricCard label="Onaylı" value={String(approved)} icon="checkmark-circle" tone={colors.green} /><MetricCard label="Bugün" value="18" icon="bicycle" tone={colors.cyan} /></FadeInView>
    <FadeInView delay={190}>
      <SectionTitle title="Canlı kurye kuyruğu" action={`${visible.length} kayıt`} />
      <View style={styles.filters}>{(['waiting', 'approved', 'all'] as Filter[]).map((item) => <AnimatedPressable key={item} containerStyle={styles.filterWrap} onPress={() => setFilter(item)}><View style={[styles.filter, filter === item && styles.filterActive]}><Text style={[styles.filterText, filter === item && styles.filterTextActive]}>{item === 'waiting' ? 'Bekleyen' : item === 'approved' ? 'Onaylı' : 'Tümü'}</Text></View></AnimatedPressable>)}</View>
      <View style={styles.list}>{visible.length ? visible.map((pass) => <View key={pass.id} style={styles.passWrap}><PassCard pass={pass} />{pass.status === 'waiting' ? <View style={styles.actions}><AnimatedPressable containerStyle={styles.actionWrap} onPress={() => reject(pass)}><View style={styles.reject}><Ionicons name="close" size={17} color={colors.red} /><Text style={styles.rejectText}>Reddet</Text></View></AnimatedPressable><AnimatedPressable containerStyle={styles.actionWrap} onPress={() => approve(pass)}><LinearGradient colors={gradients.success} style={styles.approve}><Ionicons name="shield-checkmark" size={17} color={colors.background} /><Text style={styles.approveText}>Onayla ve Kod Üret</Text></LinearGradient></AnimatedPressable></View> : pass.status === 'approved' ? <AnimatedPressable onPress={() => updatePassStatus(pass.id, 'completed')}><View style={styles.complete}><Ionicons name="checkmark-done" size={18} color={colors.purple} /><Text style={styles.completeText}>Girişi tamamla</Text></View></AnimatedPressable> : null}</View>) : <Panel style={styles.empty}><Ionicons name="shield-checkmark" size={32} color={colors.green} /><Text style={styles.emptyTitle}>Kuyruk temiz</Text><Text style={styles.emptyText}>Bu filtrede bekleyen kurye bulunmuyor.</Text></Panel>}</View>
    </FadeInView>
    <FadeInView delay={260}><SectionTitle title="Hızlı işlemler" /><View style={styles.quickRow}><Quick icon="megaphone" label="Kapı duyurusu" tone={colors.orange} /><Quick icon="qr-code" label="Kod doğrula" tone={colors.cyan} /><Quick icon="warning" label="Olay bildir" tone={colors.red} /></View></FadeInView>
  </ScrollView>;
}

function Quick({ icon, label, tone }: { icon: keyof typeof Ionicons.glyphMap; label: string; tone: string }) { return <Panel style={styles.quick}><View style={[styles.quickIcon, { backgroundColor: `${tone}18` }]}><Ionicons name={icon} size={20} color={tone} /></View><Text style={styles.quickText}>{label}</Text></Panel>; }
const styles = StyleSheet.create({ content: { padding: spacing.md, paddingTop: 12, paddingBottom: 112, gap: 20 }, header: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, eyebrow: { color: colors.green, fontSize: 9, fontWeight: '900', letterSpacing: 1 }, title: { color: colors.text, fontSize: 24, fontWeight: '900', marginTop: 3 }, subtitle: { color: colors.textSoft, fontSize: 10, marginTop: 3 }, hero: { borderRadius: radius.xl, padding: 17, flexDirection: 'row', alignItems: 'center', gap: 13 }, heroIcon: { width: 55, height: 55, borderRadius: 19, backgroundColor: 'rgba(255,255,255,.15)', alignItems: 'center', justifyContent: 'center' }, heroCopy: { flex: 1 }, heroLabel: { color: 'rgba(255,255,255,.72)', fontSize: 8, fontWeight: '900' }, heroValue: { color: colors.white, fontSize: 27, fontWeight: '900', marginTop: 2 }, heroText: { color: 'rgba(255,255,255,.78)', fontSize: 9, marginTop: 3 }, metrics: { flexDirection: 'row', gap: 9 }, filters: { flexDirection: 'row', gap: 8, marginBottom: 12 }, filterWrap: { flex: 1 }, filter: { height: 38, borderRadius: 13, borderWidth: 1, borderColor: colors.border, alignItems: 'center', justifyContent: 'center' }, filterActive: { backgroundColor: 'rgba(55,216,255,.1)', borderColor: colors.borderStrong }, filterText: { color: colors.textMuted, fontSize: 10, fontWeight: '800' }, filterTextActive: { color: colors.cyan }, list: { gap: 13 }, passWrap: { gap: 8 }, actions: { flexDirection: 'row', gap: 8 }, actionWrap: { flex: 1 }, reject: { height: 45, borderRadius: 15, borderWidth: 1, borderColor: 'rgba(255,101,125,.35)', flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 7 }, rejectText: { color: colors.red, fontSize: 10, fontWeight: '800' }, approve: { height: 45, borderRadius: 15, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 7 }, approveText: { color: colors.background, fontSize: 10, fontWeight: '900' }, complete: { height: 45, borderRadius: 15, backgroundColor: 'rgba(139,107,255,.1)', borderWidth: 1, borderColor: 'rgba(139,107,255,.3)', flexDirection: 'row', gap: 7, alignItems: 'center', justifyContent: 'center' }, completeText: { color: colors.purple, fontSize: 10, fontWeight: '900' }, empty: { alignItems: 'center', paddingVertical: 28 }, emptyTitle: { color: colors.text, fontSize: 16, fontWeight: '800', marginTop: 9 }, emptyText: { color: colors.textSoft, fontSize: 10, marginTop: 4 }, quickRow: { flexDirection: 'row', gap: 9 }, quick: { flex: 1, alignItems: 'center', paddingHorizontal: 8 }, quickIcon: { width: 40, height: 40, borderRadius: 14, alignItems: 'center', justifyContent: 'center' }, quickText: { color: colors.textSoft, fontSize: 9, fontWeight: '700', textAlign: 'center', marginTop: 8 } });
